### ISSUE TITLE
ADV-mode for Someutsushi

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-console-arcs#6]
I need to add colors for the new characters from Someutsushi before compiling the ADV-mode. Since I didn't read Someutsushi yet I don't know who these characters are. Can you tell me their names?

![chisa1_def_0](https://user-images.githubusercontent.com/539462/27288063-f3f8ed8c-5505-11e7-849c-e18050fa4b77.png)
![huji_huan_0](https://user-images.githubusercontent.com/539462/27288065-f91e306a-5505-11e7-95a5-8e02385ed739.png)
![na1_def_0](https://user-images.githubusercontent.com/539462/27288066-f9a20d4a-5505-11e7-9a9b-2283f6068f2f.png)
![tama1_def_0](https://user-images.githubusercontent.com/539462/27288097-0939b136-5506-11e7-938e-2a2bbac0861d.png)
![tomo1a_def_0](https://user-images.githubusercontent.com/539462/27288118-186cedda-5506-11e7-82cd-56fb123909e4.png)
![tou1a_def_0](https://user-images.githubusercontent.com/539462/27288125-1d102992-5506-11e7-840e-4311a9e31377.png)

**Comment by DoctorDiablo** [comment]
Characters are:

Chisato
Fujita
Natsumi
Tamako
Tomoe
Akira

**Comment by enumag** [comment]
@Aspirety All done. Download the ADV-mode patch [here](https://github.com/07th-mod/higurashi-console-arcs/archive/adv-mode.zip), replace all files. Also manually delete file CGAlt/windo_filter.png if it exists. Please report if you run into any issues.

**Comment by Aspirety** [comment]
![](http://puu.sh/wp8HH/55465f50f5.jpg)

First problem to come up is that the text box is displaying here in the chapter select screen. Doesn't display when I click it though.

![](http://puu.sh/wp8J6/2a6d252d02.jpg)

![](http://puu.sh/wp8K0/8809f23358.jpg)

There's also the issue of these icons getting in the way of the text box.

**Comment by enumag** [comment]
The textbox appearing in chapter select is minor issue, I'll look into it later.

You can hide the icons in config menu in the game.

**Comment by Aspirety** [comment]
Ah I see! If you start pushing this publicly it might be a good idea (if possible) to change that setting for users when they patch the game.

**Comment by enumag** [comment]
Unfortunately I don't know of any way to change the settings on our side. We will have to mention it in the installation guide, probably with screenshot.

**Comment by Aspirety** [comment]
![](http://puu.sh/wp9ws/8bb45da8df.jpg)

One small thing I've noticed is how the line spacing looks a bit uneven in the textlog.

**Comment by enumag** [comment]
Known/unfixable. There is another unfixable bug in the save files screen too which you'll notice later. These are limitations of the game engine, nothing we can do here. :-(

**Comment by ItaloKnox** [comment]
Have you tried to contact Doddler about these issues? I gave this suggestion before but I don't know if you did. He helped us a lot back when Onikakushi was released, we only have a patch today because he expanded a couple of features, such as the Update folder and widescreen.

If you haven't talked to him yet, maybe I can try something using Twitter. Let's just compile a list of the ten most important stuff we need to fix right now and see if he can help.

**Comment by enumag** [comment]
@ItaloKnox I tried contacting MG and got negative response. I wasn't sure how to contact Doddler directly. I'll write down a list of the known issues for your review and then PM him on twitter.

**Comment by ItaloKnox** [comment]
Looks good to me! His user should be The_Doddler, if you don't know already.

MangaGamer usually avoid these kinds of issues but as far as I know they send bug reports to him, so if they aren't willing to directly support our work (totally understandable, since they don't own the assets), maybe Doddler can manage something outside of that or just tell us what is possible and what is not possible. As far as I know we are using the same framework he also uses in Da Capo, which supports a ton of more stuff. Let's just wait and see.

**Comment by enumag** [comment]
@ItaloKnox Here is the list of issues for Doddler I came up with.

1. These are the issues and questions I consider to be most important. I would send him just these first and then maybe some more based on his response and willingnes to help.
    - Positioning of control icons for 16:9.
    - Save & Load screen bug with names.
    - Log screen issues.
    - Defining global variables.
2. Second round of issues and questions. Less important to us but would be nice to do something about it.
    - Background and images for TIPS screen.
    - Changing screen filter image based on a condition.
    - Defining custom functions with parameters.
3. Issues I don't expect to be resolved but I could ask.
    - Custom fonts.
    - Working with Unity resources (.assets files).
    - Custom tips.
    - Font styling (shadows, alignments, etc.)
4. Bugs I found in the engine which are not really important and/or possible to workaround.
    - Local variables are reset by CallScript (caused the game to freeze during Meakashi epilogue)
    - Names have to be defines in separate OutputLine calls to prevent timing issues.
    - Names blink when one character has several consecutive lines.

Anything else you would like to add? Do you agree with the order of importance?

**Comment by DoctorDiablo** [comment]
Can we get a list of the global variables the system currently uses?  I think all the config settings have a variable associated with them (I know the language setting does) so if we knew their names we could programmatically set options like the graphics setting, auto-hide UI, message box opacity, etc.

And can we get a list of functions the engine recognizes?  For example, there might be a function that can play video files, but we just don't know how to call it.

**Comment by ItaloKnox** [comment]
Well, I couldn't make a list better than that. I guess you covered everything. Let's hope we can talk to him and solve a couple of these issues. Good work!

**Comment by Grelo** [comment]
@enumag You can add a question about video? Openings etc...

**Comment by Aspirety** [comment]
I forwarded the patch to a friend and this happened, any idea why?

![](https://cdn.discordapp.com/attachments/237490860332154881/328982619276574730/unknown.png)

**Comment by ItaloKnox** [comment]
Did he clean up the ``CompiledUpdateScripts`` folder before running the game? If not, clean it and run the game again.

**Comment by Aspirety** [comment]
That seems to have fixed it~

**Comment by enumag** [comment]
I sent a twitter PM to @Doddler a week ago. He did not answer.

**Comment by ItaloKnox** [comment]
Well... at least we tried. We'll have to keep pushing these things by ourselves like we've been doing since the start.

**Comment by enumag** [comment]
I have some better news this time. I sent a tweet to Doddler today to remind him about my previous PM. He answered that he is working on a patch for Meakashi and will look into our issues to see if he can fix some of them. He is not sure about backporting them to the question arcs though.

**Comment by ItaloKnox** [comment]
Fuck yes, that's great news. Worst case scenario we leave the question arcs behind us or try to see if we can backport them manually (I have done a few stuff like this for Steam R18 patches, so I'll still try).

If we can get the glaring issues sorted out before the next chapter we'll be in a great spot to start working on ‎Tsumihoroboshi.

**Comment by vstax** [comment]
Thank you for this patch! ADV mode and these colored names look really cool.

This part https://github.com/07th-mod/higurashi-console-arcs/blob/adv-mode/Update/tips_083.txt#L18-L23 is broken and causes TIPS 83 to be skipped, it works after removing two extra "if (AdvMode) { }" and adding OutputLine call. Sorry, no patch because I'm not sure I can insert Japanese line correctly.

Also, on occasion the game "gets stuck" after switching from tips back to original story.. (black screen, system menu can't be show, but Alt-F4 shows "exit" question and allows you to exit). It seems to occur more likely when skipping, but I can't be sure about that. It's a kind of random problem, i.e. when repeating the same tip -> story transition it works fine, still, I had this happen 2 or 3 times. This never happened in NVL mode before TIPS introduction, so it must be caused by either TIPS or ADV mode..

**Comment by enumag** [comment]
I'll fix the first issue right away, thanks for reporting.

The second issue seems too unreliable. Maybe I'll do something about it when I actually play Some myself if I can reproduce it.

**Comment by enumag** [comment]
Can you upload your output_log.txt after experiencing the second issue and closing the game? Maybe that will give us a clue. You'll find it in the same directory as StreamingAssets.

**Comment by vstax** [comment]
@enumag Unfortunately, I can't seem to reproduce it. However, I found another problem when trying to read omake. The result is the same (black screen, only Alt-F4 works) but this error is stable so it must be a broken script or something.
Here is log file: https://pastebin.com/2Y39Rirt
(I loaded save made in last line of last chapter, skipped tips 087 and picked omake; the same happens if reading the tip, then trying to read omake).

Out of curiosity: why does the game tries to play `SE/wa_038.ogg` and `SE/sysse02.ogg` (according to log file)? There are no references to these in either Someutsushi or original Himatsubishi scripts! First one is 1 second clip from Watanagashi and I can't seem to find second one anywhere. Am I supposed to copy the first one from Watanagashi for "better experience"?

**Comment by enumag** [comment]
Omake should be fixed now.

I think wa_038 is played when you click in menu or something. No idea why it's not found, it exists in Hima. For sysse02 I have no idea. Can't find such file anywhere.

**Comment by DoctorDiablo** [comment]
Ah.  My installation instructions have you delete the SE folder to clear out all the unused audio, so that's why the file is not there.  I'll try to identify any audio files that the menus use and make sure they are included with the package in the future.

**Comment by enumag** [comment]
@DoctorDiablo Once again we have a lot of things from the main games to update here too. Let us know when you're done with the Kage translation, I just need to run a few commands to enable ADV-mode for Kage and update both arcs with the new features. Let's make an official Kage release after that. I'll also most likely read both chapters myself at that time.

**Comment by DoctorDiablo** [comment]
@enumag Awesome, sounds like a plan.  I still have a lot of translating to do, so no rush.

We need to create an installer for these too.  I never got around to setting that up when I put together the Some release.

**Comment by enumag** [comment]
@ItaloKnox Would you be willing to make the installer when the time comes? I mean from the team you have the most experience with those.

**Comment by ItaloKnox** [comment]
Yeah, shouldn't be an issue. Just ping me when it's ready. I can reuse the source from Hima and just adjust it accordingly.

**Comment by ZLTM** [comment]
Hello i just discovered this project and would like to help with the development.
After contacting with Italo Bruno he told me to post a message here.
I have experience with Unity3D, I can talk in english, spanish and some japanese
So there is any list of bugs or pending features I could help with in the console arcs or any other Higurashi related project?

**Comment by DoctorDiablo** [comment]
@ZLTM Yeah.  The biggest hangup for the console arcs is just that I'm really slow at translating stuff, but there are some issues you could look into.  Since you have experience with Unity, maybe you can figure out how to [replace images in the assets file](https://github.com/07th-mod/himatsubushi/issues/10) or fix the [red x issue](https://github.com/07th-mod/higurashi-console-arcs/issues/2)

**Comment by enumag** [comment]
@ZLTM I was about to link you to the same issues as @DoctorDiablo just did.

Aside from these issues it's probably a question of how good is your japanese. Do you think it's good enough to help with translation of the console arcs to english? Currently @DoctorDiablo is the only one of our group capable of translating them and it's the main thing that's slowing down the project.

Also all the console arcs first need to be ported from the PS3 version to MG engine before the translation even begins. @DoctorDiablo has been handling that so far, I'm not sure if he needs any help on that front.

Other of our long-pending issues include [lipsync](https://github.com/07th-mod/higurashi-patch-compiler/issues/9). Do you know if Unity has something we could use to implement that?

Then there is the thing of [PS3 video opening](https://github.com/07th-mod/onikakushi/issues/68). Do you know how to get that working with Unity?

Also there is the problem of [changing himatsubushi-related stuff](https://github.com/07th-mod/higurashi-console-arcs/issues/3) like game name in title bar for the console arcs. Even with DLL-hacking @P-Chang was so far unable to fix these. Do you have a way to determine where a Unity-based game stores such things so that we could change those?

Aside from this long-term wishlist most of our work is porting the PS3 backgrounds and sprites to the games as they come out by MG, making a matching graphics patch from the new MG sprites, adding PS2/PS3 voices, writing scripts to do certain tasks like ADV-mode transformation automatically, DLL-hacking to fix issues in the base games and finally testing the game thoroughly to fix every little issue we can find (only Tata and Hima are truly polished right now). Also there are some efforts to find PS3-only scenes and dialogue changes and port them to our mods. If the changes include censorship we make a condition so that the game can go either way based on the player's preference.

One thing I'm kind of thinking about but never got to do was making an alternative set of background music, maybe using tracks from Higurashi anime.

That's about everything I can think of from the top of my head. It's just to give you the gist of what we do and where we would appreciate some help. If you want to help with any of the things I mentioned, let us know.

And most importantly if you have some ideas of your own what we could improve, please tell us. Maybe we can push it forward together.

**Comment by P-Chang** [comment]
@DoctorDiablo 
I already found soulution for AssetBundle texture replacement in https://github.com/07th-mod/higurashi-patch-compiler/issues/5 .

@ZLTM 
I mainly hack Assembly-CSharp.dll with dNSpy. But my C# knowledge is really cheap, so I'm really happy if C# coder help these works.

dNSpy is really helpful software, but modding many code with this are bit bother work than coding with VS or Unity.

We can't compile entire code or class or namespace(sometimes it break dll), Editing vanilla filed make logger bad, add argument make dll break... etc

And recompile vanilla method make code to unreadable code sometimes. so I leave many backup.
If you help this, I'll re-arrangement these backups.

Although I assume many feature of Unity can't use without Unity GUI, is it true?

Red X issue https://github.com/07th-mod/higurashi-console-arcs/issues/2 that @DoctorDiablo  told are related in font that was set by TextMeshPro didn't support these character. Do you know how to improve  TextMeshPro font that was already authorized? 

Or I think these chinese character are antique. replacement is enough if we could.

**Comment by ZLTM** [comment]
My japanese is not really in the level of 07 writing yet, i would like to see into it but mostly as an educational experience, not planing on upload a bad translation.

About unity3D, it really depends, if the game was made in unity and we have the files used for compilation then it would be a great tool for the job, if not we are better sticking with a C# IDE or text editor, or any other engine they used if available.
Manga gamer talks a litle about the engine in this article
http://blog.mangagamer.org/2015/05/25/building-a-better-higurashi/
But they dont say anything conclusive, it would be great if someone knows what engine is being used for sure.

The same goes for the lipsinc, if the game was developed using an asset we could just use it, if not it may complicate things.

I will look into these, this is my first time colaborating trought github with a remote team in a project already in process so i want to be carefull and dont touch something i sould not lol

**Comment by enumag** [comment]
@ZLTM It's not like @DoctorDiablo is a professional translator either. No offence to him meant, it's just that this is his first translation project and we did get some feedback about the translation not being very good. But he is improving and edits the translation several times before he is finished. He really puts in a LOT of effort. Maybe you could try translate a bit and he could review if it's good enough for us? Just an idea.

I'm quite sure we don't have the files used for compilation. I don't think the engine has a name. It's probably something unique to Higurashi. It is modding-friendly in most aspects though as the images, sounds and scripts are all in separate files and the scripts are human-readable, not just the compiled version of them. I suspect that MG did that intentionally. The issues I linked above are mostly those that need to go beyond the engine's modding limitations and will likely require DLL hacking or good experience with how things works in Unity-based engines. @P-Chang already solved the easy bugs so only the more difficult issues are left. Don't worry about it if you're unable to help with them, We don't have any high expectations from you (yet). It's just that the easy issues are all taken care of by now since the project was active for years now. So only the difficult problems are left. And those tiny issues like missing names, voices etc. here and there - I'm still finding a lot of those when I playthe games.

You don't need to be too careful. Feel free to experiment with anything you find and ask questions. You don't have the privileges to break anything yet anyway and we will review your changes before accepting them.

**Comment by ItaloKnox** [comment]
Just to add a bit to the engine talk, it's actually a framework made by Doddler in Unity. The newest Da Capo game should use the same framework as the base but with a lot more stuff, so maybe we could try looking at the code?

**Comment by DoctorDiablo** [comment]
@enumag I finally finished translating everything in Kage.  Can you run your scripts to do the ADV conversion now?  I still need to read through the whole thing to do editing, but it would be good to test out the ADV stuff at the same time so I can fix any issues from the conversion.

**Comment by enumag** [comment]
@DoctorDiablo Compiled and pushed into the adv-mode branch. Note that this does not require our updated DLLs yet. I'll proably do that update for both console arcs when we finish lip-sync.

Would it be possible to separate the console arcs by directory? Like:

```
Update/
    init.txt
    chapterselect.txt
    some/
        some_001.txt
    kage/
...
```

**Comment by P-Chang** [comment]
it is impossible. compiler never search sub directory.

I'll look over it, probably it will come after lip-sync. but some user system will fail this process.

**Comment by DoctorDiablo** [comment]
Cool, I grabbed the new scripts from the ADV branch and dropped everything on top of a clean install of Hima from the installer.  It looks like it's working well so far:
![image](https://user-images.githubusercontent.com/20390474/33796970-273e4706-dccd-11e7-971a-2509a70dcac4.png)

One problem I had is that I put the voices in the voice folder, but the script is still using PlaySE so they weren't playing.  Is the voice folder still in development, or do we need to replace all the voice lines in the script with PlayVoice?

@P-Chang No rush on getting the subdirectory thing to work.  I work really slow, so there won't be any new scripts for a while.

@enumag Going forward from here, I guess I should keep pushing my changes to the master branch and you can pull them into ADV.  Then once we've got everything stabilized, we can make the ADV branch the main branch.

**Comment by P-Chang** [comment]
@DoctorDiablo 
PlaySE can use only SE folder, and PlayVoice can use only voice folder.
If you use vanilla DLL in development, chapter4 vanilla PlayVoice was broken, so you can't use it.

Patched DLL probably can handle vanilla scripts, so if you never press F1, you can use patched DLL in development.

If you want vanilla DLL with only PlayVoice support, I can send it to you. fixing playvoice is not hard work.

**Comment by DoctorDiablo** [comment]
@P-Chang Don't worry about it, I can do my testing with what I've got and we can integrate it with the patched DLL and your most recent changes later.

**Comment by enumag** [comment]
@P-Chang Oh. Thanks for explaining. You can look into it if you want but consider it low priority (lower than lip-sync).

@DoctorDiablo 

As for voices, that is related to the DLL changes which we'll do later for console arcs. For now put voices to SE directory.

At this point it does not matter which branch you push your changes to. Pushing changes to master was prefered before when I was constantly making changes to the ADV-mode compiler. Now I didn't change anything in the ADV compiler for months so I consider it quite stable. It is very unlikely that I'd need to recompile the whole thing again. Choose whichever branch is easier for you to work with.

**Comment by DoctorDiablo** [comment]
@enumag I finished editing Kageboushi, so you're free to recompile the script or merge the changes in.  Whatever you need to do.

I also started looking into why ADV mode was failing in the tips, and I found two problems:
1. tips_083.txt had a weird formatting problem with a nested if statement.  None of the other tips had this problem, so I'm not sure what's going on here, but I managed to fix this manually:

```
	if (AdvMode) {
		if (AdvMode) { OutputLineAll("", NULL, Line_ContinueAfterTyping); }
				NULL, "<size=-2>Around 1:30 AM on the 25th, a fire broke out in a two-story wooden flat owned by Yuusuke Minai-san (43), the chief inspector of the Setagaya district police department. Approximately 170 square meters of property were burned down.</size>", Line_Normal);
	} else {
		if (AdvMode) { OutputLineAll("", NULL, Line_ContinueAfterTyping); }
				NULL, "Around 1:30 AM on the 25th, a fire broke out in a two-story wooden flat owned by Yuusuke Minai-san (43), the chief inspector of the Setagaya district police department. Approximately 170 square meters of property were burned down.", Line_Normal);
	}
```

2. None of the tips have AdvMode defined at the top of the file.  I think I just need to add this at the top of each of them.
```
	int AdvMode;
	AdvMode = 1;
	int Line_ModeSpecific;
	if (AdvMode) {
		Line_ModeSpecific = Line_Normal;
	} else {
		Line_ModeSpecific = Line_WaitForInput;
	}
```

**Comment by enumag** [comment]
I'll look into it over the christmas break. Not sure when exactly. Big thanks to you for the translation!

**Comment by DoctorDiablo** [comment]
Well, defining AdvMode in each of the tips didn't work.  It just complained that a variable with that name was already defined.

I think the problem only happens when I have multiple tips in a row, which only actually happens in some_007 and kage_007.  Script X calls tip 1, tip 1 has AdvMode defined properly, tip 1 finishes and returns control back to script X, but at that point AdvMode is no longer defined, so when script X calls tip 2 it blows up saying AdvMode is not defined.

**Comment by enumag** [comment]
@DoctorDiablo Don't worry about it, these are the limitations of the original engine. With our updated DLLs ADV mode works in completely different way and these problems will be gone.

**Comment by enumag** [comment]
@DoctorDiablo Are there any new characters in Kageboshi? If so I need to add ADV-mode name colors for them.

**Comment by enumag** [comment]
@ItaloKnox I messed up branches in this repo a little. I'll need more privileges to fix it.

**Comment by ItaloKnox** [comment]
Give me a minute.

**Comment by ItaloKnox** [comment]
@enumag there you go, you should have access to the whole thing now. You're now my backup in case I'm hit by a truck or something.

**Comment by enumag** [comment]
@ItaloKnox Thank you. I don't think I can replace you though. So no jumping under a truck, ok? :-)

**Comment by ItaloKnox** [comment]
Hahahahaha, I don't plan to. I want to see this through, I love what we created.

**Comment by enumag** [comment]
Alright guys, I'm done with the upgrade. Here is how to install the finished patch:

1. Install Himatsubushi.
2. Upgrade it using our Himatsubushi patch (because we need new DLL).
3. Download and apply console arcs [v2.0](https://github.com/07th-mod/higurashi-console-arcs/releases/tag/2.0) patch.
4. Download zip of the dll-update branch in this repository and replace the Update directory, 
5. Move voices from SE to voice directory.

Everything should work smoothly then.

Now would be a good time to make a new patch with moved voices, added DLL etc. and possibly an installer for the console arcs patch.

**Comment by DoctorDiablo** [comment]
I did some testing, so I'm satisfied everything is working in ADV mode.  I'm gonna mark this closed now.  If we run into any other issues with ADV mode or anything related, we can open more specific issues for those.

Nice work with the dll updates!
